### ISSUE TITLE
不知道为什么只要一打开就会弹出无法连接到github。

### ISSUE THREAD

**Issue by keeely12450** [shanchuan001/MET#1]
不管是开了梯子还是怎样都没效果（（（

**Comment by shanchuan001** [comment]
那是[MFAWPF](https://github.com/SweetSmellFox/MFAWPF)还未写完的自动更新功能.不用在意,没有影响
现在应该已经不会弹了

**Comment by keeely12450** [comment]
> 那是[MFAWPF](https://github.com/SweetSmellFox/MFAWPF)还未写完的自动更新功能.不用在意,没有影响 现在应该已经不会弹了

顺便我为啥进入新版协力，它填完300把之后就自动结束完成任务了（
不应该是进入之后就自动按开始了吗？
